name: pieblock_core
description: PIE-Block 的项目模型、静态检查与 C 代码生成核心。
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.13.1

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
